Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Metrics/LineLength:
  Max: 123

Style/BlockComments:
  Enabled: false

inherit_from: .rubocop_todo.yml
